# Generated by Django 3.0.4 on 2020-03-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200325_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createshoprecommendation',
            name='extra_instruction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='createshoprecommendation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
