# Generated by Django 3.0.4 on 2020-03-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createshoprecommendation',
            name='recommended_for',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createshoprecommendation',
            name='user_id',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
