# Generated by Django 2.2 on 2020-03-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200326_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acceptor',
            new_name='Accepts',
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='location',
            field=models.CharField(default='vellore', max_length=100),
            preserve_default=False,
        ),
    ]
