# Generated by Django 2.2 on 2020-03-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_itemrequest_accepted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepts',
            name='item_names',
            field=models.CharField(default='item', max_length=10000),
            preserve_default=False,
        ),
    ]
