# Generated by Django 2.2 on 2020-03-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200331_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='description',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='address',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='other_contact',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='web_links',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
