# Generated by Django 2.2 on 2020-04-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200401_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
