# Generated by Django 2.2 on 2020-04-12 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200407_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasCatered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Organizations')),
            ],
        ),
    ]
