# Generated by Django 2.2 on 2020-04-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0002_auto_20200409_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfcmdevice',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
