# Generated by Django 2.2 on 2020-04-12 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0003_auto_20200413_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfcmdevice',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
