# Generated by Django 2.2 on 2020-04-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfcmdevice',
            name='registration_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='userfcmdevice',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
