# Generated by Django 2.2 on 2020-03-26 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_made_by', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acceptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_made_by', models.CharField(max_length=255)),
                ('request_acceptor', models.CharField(max_length=255)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Request')),
            ],
        ),
    ]
