# Generated by Django 2.2 on 2020-03-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    atomic = False

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='ItemRequest',
            
        ),
        
    ]
