# Generated by Django 2.2 on 2020-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200330_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='accepted_by',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
