# Generated by Django 2.2 on 2020-03-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_accepts_item_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='address',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='other_contact',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='web_links',
            field=models.TextField(default=None, null=True),
        ),
    ]
